nusc_exp_mgr_node:
  ros__parameters:
    exp_configs: ['config/greedy_bestdist_bestmodel_bestmgmt.yaml',
                  'config/greedy_iou3d_bestmodel_bestmgmt.yaml',
                  'config/greedy_giou3d_bestmodel_bestmgmt.yaml']

    val_dataset: 'v1.0-trainval'
    val_split: 'val'
    mcap_dir: 'nuscenes/mcap' # relative to home directory
    results_dir: 'tracking_ws/src/marmot/results/3b_best' # relative to home directory
    det_topic: '/detections'
    track_topic: '/tracks'
    lidar_detector: 'megvii'