nusc_exp_mgr_node:
  ros__parameters:
    exp_configs: ['config/greedy_dist2_cvcy_count_yc.yaml',
                  'config/greedy_iou3d_cvcy_count_yc.yaml',
                  'config/greedy_giou3d_cvcy_count_yc.yaml']

    val_dataset: 'v1.0-mini'
    val_split: 'mini_train'
    mcap_dir: 'nuscenes/mcap' # relative to home directory
    results_dir: 'tracking_ws/src/marmot/results/1_sim_metrics' # relative to home directory
    det_topic: '/detections'
    track_topic: '/tracks'
    lidar_detector: 'megvii'