nusc_exp_mgr_node:
  ros__parameters:
    exp_configs: ['config/greedy_dist5_bestmodel_conf_padd_15_noyc.yaml',
                  'config/greedy_dist5_bestmodel_conf_padd_15_yc.yaml',
                  'config/dist_bestval.yaml',
                  'config/dist2_bestval.yaml',
                  'config/dist5_bestval.yaml',
                  'config/dist10_bestval.yaml',
                  'config/dist_bestval_yc.yaml',
                  'config/dist2_bestval_yc.yaml',
                  'config/dist5_bestval_yc.yaml',
                  'config/dist10_bestval_yc.yaml']
    # exp_configs: ['config/greedy_dist2_bestmodel_count_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_padd_05_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_padd_10_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_padd_15_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_padd_20_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_padd_25_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_padd_30_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_padd_40_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_padd_50_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_mult_05_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_mult_10_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_mult_15_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_mult_20_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_mult_25_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_mult_30_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_mult_40_noyc.yaml',
    #               'config/greedy_dist2_bestmodel_conf_mult_50_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_count_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_padd_05_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_padd_10_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_padd_15_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_padd_20_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_padd_25_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_padd_30_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_padd_40_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_padd_50_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_mult_05_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_mult_10_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_mult_15_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_mult_20_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_mult_25_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_mult_30_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_mult_40_noyc.yaml',
    #               'config/greedy_dist5_bestmodel_conf_mult_50_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_count_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_padd_05_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_padd_10_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_padd_15_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_padd_20_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_padd_25_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_padd_30_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_padd_40_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_padd_50_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_mult_05_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_mult_10_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_mult_15_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_mult_20_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_mult_25_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_mult_30_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_mult_40_noyc.yaml',
    #               'config/greedy_dist10_bestmodel_conf_mult_50_noyc.yaml']

    val_dataset: 'v1.0-trainval'
    val_split: 'val'
    mcap_dir: 'nuscenes/mcap' # relative to home directory
    results_dir: 'tracking_ws/src/marmot/results' # relative to home directory
    det_topic: '/detections'
    track_topic: '/tracks'
    lidar_detector: 'megvii'