nusc_exp_mgr_node:
  ros__parameters:
    exp_configs: ['config/hungar_dist10_cvcy_count.yaml',
                  'config/greedy_dist10_cvcy_count.yaml',
                  'config/hungar_dist10_cvcy_obj_count.yaml',
                  'config/greedy_dist10_cvcy_obj_count.yaml',
                  'config/hungar_dist10_ack_count.yaml',
                  'config/greedy_dist10_ack_count.yaml',
                  'config/hungar_dist5_cvcy_count.yaml',
                  'config/greedy_dist5_cvcy_count.yaml',
                  'config/hungar_dist5_cvcy_obj_count.yaml',
                  'config/greedy_dist5_cvcy_obj_count.yaml',
                  'config/hungar_dist5_ack_count.yaml',
                  'config/greedy_dist5_ack_count.yaml',
                  'config/hungar_dist2_cvcy_count.yaml',
                  'config/greedy_dist2_cvcy_count.yaml',
                  'config/hungar_dist2_cvcy_obj_count.yaml',
                  'config/greedy_dist2_cvcy_obj_count.yaml',
                  'config/hungar_dist2_ack_count.yaml',
                  'config/greedy_dist2_ack_count.yaml']
                  
    val_dataset: 'v1.0-mini'
    val_split: 'mini_train'
    mcap_dir: 'nuscenes/mcap' # relative to home directory
    results_dir: 'tracking_ws/src/marmot/results' # relative to home directory
    det_topic: '/detections'
    track_topic: '/tracks'
    lidar_detector: 'megvii'